// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories;

#nullable disable

namespace EmployeeApi.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20240103081318_addGender")]
    partial class addGender
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("Entities.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Salary")
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            FirstName = "Eren",
                            Gender = true,
                            LastName = "Güven",
                            Salary = 50000m
                        },
                        new
                        {
                            EmployeeId = 2,
                            FirstName = "İrem",
                            Gender = false,
                            LastName = "Bulut",
                            Salary = 60000m
                        },
                        new
                        {
                            EmployeeId = 3,
                            FirstName = "Bahar",
                            Gender = false,
                            LastName = "Güneş",
                            Salary = 40000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
